# Generated by Django 5.1.7 on 2025-04-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_userprofile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="food_type",
            field=models.CharField(
                choices=[
                    ("vegetarian", "Vegetarian"),
                    ("non-vegetarian", "Non-Vegetarian"),
                ],
                default="vegetarian",
                max_length=20,
            ),
        ),
    ]
